import libraryData from './library.json'
import { isPlainObject, type JsonObject } from '../lib/json'

/** A library record as generated by scripts/build-flutter-cloudflare-data.mjs. */
export interface LibraryRecord {
  id: string
  n: string
  bp: string
  tg: string
  eq: string
  sm: string[]
  bp_es: string
  tg_es: string
  eq_es: string
  sm_es: string[]
  st_es: string[]
}

/** A custom exercise in the plan doc, always in the full shape of data-B3. */
export interface CustomExercise {
  id: string
  n: string
  bp: string
  desc: string
  tg: ''
  eq: 'custom'
  custom: true
  [extra: string]: unknown
}

/** One exercise as the MCP tools see it: a library record or a custom exercise. */
export interface CatalogExercise {
  id: string
  name: string
  bodyPart: string
  target: string
  equipment: string
  secondary: string[]
  bodyPart_es: string
  target_es: string
  equipment_es: string
  secondary_es: string[]
  instructions_es: string[]
  custom: boolean
  /** Custom exercises only: the owner's description (untrusted text). */
  desc?: string
}

export const LIBRARY: readonly LibraryRecord[] = libraryData as LibraryRecord[]

export const LIBRARY_BY_ID: ReadonlyMap<string, LibraryRecord> = new Map(LIBRARY.map(record => [record.id, record]))

const BODY_PART_ES: ReadonlyMap<string, string> = new Map(LIBRARY.map(record => [record.bp, record.bp_es]))

export const CUSTOM_EQUIPMENT_ES = 'personalizado'

/**
 * Normalises any custom-exercise record to the one shape every writer uses (data-B3), keeping
 * unknown keys. Returns null for records without an id.
 */
export function normalizeCustomExercise(raw: unknown): CustomExercise | null {
  if (!isPlainObject(raw) || typeof raw.id !== 'string' || raw.id === '') return null
  return {
    ...raw,
    id: raw.id,
    n: typeof raw.n === 'string' ? raw.n : String(raw.n ?? ''),
    bp: typeof raw.bp === 'string' ? raw.bp : '',
    desc: typeof raw.desc === 'string' ? raw.desc : '',
    tg: '',
    eq: 'custom',
    custom: true,
  }
}

/** The plan doc's `customEx`, normalised; invalid entries are dropped. */
export function customExercisesOf(plan: JsonObject): CustomExercise[] {
  const list = Array.isArray(plan.customEx) ? plan.customEx : []
  return list.map(normalizeCustomExercise).filter((c): c is CustomExercise => c !== null)
}

function fromLibrary(record: LibraryRecord): CatalogExercise {
  return {
    id: record.id,
    name: record.n,
    bodyPart: record.bp,
    target: record.tg,
    equipment: record.eq,
    secondary: record.sm,
    bodyPart_es: record.bp_es,
    target_es: record.tg_es,
    equipment_es: record.eq_es,
    secondary_es: record.sm_es,
    instructions_es: record.st_es,
    custom: false,
  }
}

function fromCustom(custom: CustomExercise): CatalogExercise {
  return {
    id: custom.id,
    name: custom.n,
    bodyPart: custom.bp,
    target: '',
    equipment: 'custom',
    secondary: [],
    bodyPart_es: BODY_PART_ES.get(custom.bp) ?? custom.bp,
    target_es: '',
    equipment_es: CUSTOM_EQUIPMENT_ES,
    secondary_es: [],
    instructions_es: [],
    custom: true,
    desc: custom.desc,
  }
}

const LIBRARY_EXERCISES: readonly CatalogExercise[] = LIBRARY.map(fromLibrary)

/** The library merged with the owner's custom exercises (customs first, as in the original). */
export class Catalog {
  readonly exercises: readonly CatalogExercise[]
  private readonly byId: ReadonlyMap<string, CatalogExercise>

  constructor(customs: readonly CustomExercise[] = []) {
    // A custom exercise can never shadow a library id.
    const own = customs.filter(custom => !LIBRARY_BY_ID.has(custom.id)).map(fromCustom)
    this.exercises = [...own, ...LIBRARY_EXERCISES]
    this.byId = new Map(this.exercises.map(exercise => [exercise.id, exercise]))
  }

  static forPlan(plan: JsonObject): Catalog {
    return new Catalog(customExercisesOf(plan))
  }

  get(id: string): CatalogExercise | undefined {
    return this.byId.get(id)
  }

  has(id: string): boolean {
    return this.byId.has(id)
  }

  bodyPartOf(id: string): string | undefined {
    return this.byId.get(id)?.bodyPart
  }

  /** `modeOf` of the original (data-model §1.3): an explicit mode, else cardio by body part, else reps. */
  modeOf(cfg: { id?: unknown; mode?: unknown } | null | undefined): ExerciseMode {
    const mode = cfg?.mode
    if (mode === 'reps' || mode === 'time' || mode === 'cardio') return mode
    return typeof cfg?.id === 'string' && this.bodyPartOf(cfg.id) === 'cardio' ? 'cardio' : 'reps'
  }

  search(query: ExerciseQuery = {}): CatalogExercise[] {
    return searchExercises(this.exercises, query)
  }
}

export type ExerciseMode = 'reps' | 'time' | 'cardio'

/** Lowercase, accents removed, whitespace collapsed: the comparison form for searches. */
export function foldText(text: string): string {
  return text
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim()
}

export interface ExerciseQuery {
  /** Free text: every word must match the English name, target, equipment, body part or a Spanish label. */
  query?: string
  /** English or Spanish body part, e.g. `chest` or `pecho`. */
  bodyPart?: string
  /** English or Spanish target muscle. */
  target?: string
  /** Any of these equipment values (English or Spanish). Custom exercises always pass. */
  equipment?: readonly string[]
  /** Default 25, at most 100. */
  limit?: number
}

export const SEARCH_DEFAULT_LIMIT = 25
export const SEARCH_MAX_LIMIT = 100

function matchesLabel(filter: string | undefined, ...labels: string[]): boolean {
  if (!filter) return true
  const wanted = foldText(filter)
  return labels.some(label => foldText(label) === wanted)
}

/** Lower is better: exact name, name prefix, all words in the name, words found in other fields. */
function nameRank(exercise: CatalogExercise, folded: string, words: string[]): number {
  const name = foldText(exercise.name)
  if (name === folded) return 0
  if (name.startsWith(folded)) return 1
  if (words.every(word => name.includes(word))) return 2
  return 3
}

/**
 * `search_exercises` semantics (contract §5.2): customs first, then the library; case- and
 * accent-insensitive; results ranked by how well the name matches, then catalogue order.
 */
export function searchExercises(exercises: readonly CatalogExercise[], query: ExerciseQuery = {}): CatalogExercise[] {
  const folded = foldText(query.query ?? '')
  const words = folded ? folded.split(' ') : []
  const equipment = (query.equipment ?? []).map(foldText).filter(Boolean)
  const limit = Math.min(SEARCH_MAX_LIMIT, Math.max(1, Math.floor(query.limit ?? SEARCH_DEFAULT_LIMIT)))

  const matches = exercises.filter(exercise => {
    if (!matchesLabel(query.bodyPart, exercise.bodyPart, exercise.bodyPart_es)) return false
    if (!matchesLabel(query.target, exercise.target, exercise.target_es)) return false
    if (equipment.length > 0 && !exercise.custom) {
      const own = [foldText(exercise.equipment), foldText(exercise.equipment_es)]
      if (!equipment.some(value => own.includes(value))) return false
    }
    if (words.length === 0) return true
    const haystack = foldText(
      [exercise.name, exercise.target, exercise.equipment, exercise.bodyPart, exercise.bodyPart_es, exercise.target_es, exercise.equipment_es, exercise.desc ?? ''].join(' | '),
    )
    return words.every(word => haystack.includes(word))
  })

  const ranked = matches.map((exercise, index) => ({ exercise, index, rank: words.length ? nameRank(exercise, folded, words) : 0 }))
  ranked.sort((a, b) => Number(b.exercise.custom) - Number(a.exercise.custom) || a.rank - b.rank || a.index - b.index)
  return ranked.slice(0, limit).map(entry => entry.exercise)
}
